### PR TITLE
Add TIL for HDFS

### PR DESCRIPTION
**Pull request by matthewmarcos**

### CODE REVIEW

**Comment by ace-subido** [comment]
Change the README as well, add this under the "HDFS" section

**Comment by ace-subido** [comment]
- change file from `hadoop-hdfs/basic-hdfs-til-matt.md` to `hadoop-hdfs/basic-hdfs.md`
- Change title from HDFS TIL to "Basic HDFS"
- Check formatting. Click "View" or use something like "Mou" to edit Markdown files.

til_basic-hdfs-til-matt_md_at_e5406edd4254e4fe2f48208d18a7effb6c8526f3_ _matthewmarcos94_til

**Comment by matthewmarcos** [comment]
Weird. This is what I got on my screen: 
md problemo

Anyway I just turned them into links

**Comment by ace-subido** [comment]
👍

**Pull request merged**
